version: '3'
services:

  mongodb:
    image: mongo:3.0.4
    command: --smallfiles --master
    ports:
      - "27017:27017"


  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.30.0.M8
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888


  kafka:
    image: eventuateio/eventuateio-local-kafka:0.30.0.M8
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  mysql:
    image: eventuateio/eventuate-tram-sagas-mysql:0.10.0.M2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw


  cdc-service:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.20.0.M7
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_CDC_PIPELINE_PROPERTIES: >
        [{"type":"eventuate-local",
        "sourceTableName":"events",
        "reader":"reader1"},
        {"type":"eventuate-tram",
        "reader":"reader1"}]
      EVENTUATE_CDC_PIPELINE_READER_PROPERTIES: >
        [{"type":"mysql-binlog",
        "name":"reader1",
        "dataSourceUrl":"jdbc:mysql://mysql/eventuate",
        "dataSourceUserName":"mysqluser",
        "dataSourcePassword":"mysqlpw",
        "dataSourceDriverClassName":"com.mysql.jdbc.Driver",
        "leadershipLockPath":"/ftgo/cdc/leader/reader/1",
        "cdcDbUserName":"root",
        "cdcDbPassword":"rootpassword",
        "oldDebeziumDbHistoryTopicName":"none",
        "binlogClientId": 1,
        "mySqlBinLogClientName": "MySqlBinLog"}]

#  customer-service:
#    build: ./customer-service
#    depends_on:
#      - cdc-service
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      JAVA_OPTS: -Xmx192m
#      EUREKA_HOST: eureka-server
## end container
#  api-gateway-service:
#    build: ./api-gateway-service
#    ports:
#      - "8080:8080"
#    environment:
#      CUSTOMER_SERVICE_URL: http://customer-service:8081
#      ACCOUNT_SERVICE_URL: http://account-service:8082
#      MONEY_TRANSFER_SERVICE_URL: http://money-transfer-service:8083
#      CUSTOMER_VIEW_SERVICE_URL: http://customer-view-service:8084
#      ACCOUNT_GROUP_SERVICE_URL: http://account-group-service:8085
#      EUREKA_HOST: eureka-server
#      JAVA_OPTS: -Xmx192m
## end container
#  account-service:
#    build: ./account-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - cdc-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      JAVA_OPTS: -Xmx192m
#      EUREKA_HOST: eureka-server
## end container
#  money-transfer-service:
#    build: ./money-transfer-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      - cdc-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      JAVA_OPTS: -Xmx192m
#      EUREKA_HOST: eureka-server
## end container
#  customer-view-service:
#    build: ./customer-view-service
#    depends_on:
#      - cdc-service
#    ports:
#      - "8084:8084"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#      SPRING_DATA_MONGODB_URI: mongodb://mongodb/bankingexampledb
#      EUREKA_HOST: eureka-server
#      JAVA_OPTS: -Xmx192m
## end container
#  account-group-service:
#      build: ./account-group-service
#      depends_on:
#        - cdc-service
#      ports:
#        - "8085:8085"
#      environment:
#        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
#        EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#        EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#        JAVA_OPTS: -Xmx192m
#        EUREKA_HOST: eureka-server
## end container
