apiVersion: v1
kind: Service
metadata:
  name: ftgo-mysql
  labels:
    name: ftgo-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    role: ftgo-mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ftgo-mysql
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        role: ftgo-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ftgo-mysql
          image: eventuateio/eventuate-tram-sagas-mysql:0.10.0.M2
          imagePullPolicy: IfNotPresent
          args:
              - "--ignore-db-dir=lost+found"
          ports:
              - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-root-secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: password
---
