apiVersion: v1
kind: Service
metadata:
  name: ftgo-tram-cdc-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    svc: ftgo-tram-cdc-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ftgo-tram-cdc-service
  labels:
    application: ftgo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: ftgo-tram-cdc-service
    spec:
      containers:
      - name: ftgo-tram-cdc-service
        image: eventuateio/eventuate-tram-cdc-mysql-service:0.20.0.M7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: httpport
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx192m -Dsun.net.inetaddr.ttl=30 -verbose:gc"
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: ftgo-kafka:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: ftgo-zookeeper:2181
          - name: EVENTUATE_CDC_PIPELINE_PROPERTIES
            value: >
              [{"type":"eventuate-local",
              "sourceTableName":"events",
              "reader":"reader1"},
              {"type":"eventuate-tram",
              "reader":"reader1"}]
          - name: EVENTUATE_CDC_PIPELINE_READER_PROPERTIES
            value: >
              [{"type":"mysql-binlog",
              "name":"reader1",
              "dataSourceUrl":"jdbc:mysql://ftgo-mysql/eventuate",
              "dataSourceUserName":"mysqluser",
              "dataSourcePassword":"mysqlpw",
              "dataSourceDriverClassName":"com.mysql.jdbc.Driver",
              "leadershipLockPath":"/ftgo/cdc/leader/reader/1",
              "cdcDbUserName":"root",
              "cdcDbPassword":"rootpassword",
              "oldDebeziumDbHistoryTopicName":"none",
              "binlogClientId": 1,
              "mySqlBinLogClientName": "MySqlBinLog"}]
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
---
